export const second = [
  {
    code: "KeyA",
    keyBig: "A",
    keySmall: "a",
    keyBigUa: "Ф",
    keySmallUa: "ф",
    view: "standart",
  },
  {
    code: "KeyS",
    keyBig: "S",
    keySmall: "s",
    keyBigUa: "І",
    keySmallUa: "і",
    view: "standart",
  },
  {
    code: "KeyD",
    keyBig: "D",
    keySmall: "d",
    keyBigUa: "В",
    keySmallUa: "в",
    view: "standart",
  },
  {
    code: "KeyF",
    keyBig: "F",
    keySmall: "f",
    keyBigUa: "А",
    keySmallUa: "а",
    view: "standart",
  },
  {
    code: "KeyG",
    keyBig: "G",
    keySmall: "g",
    keyBigUa: "П",
    keySmallUa: "п",
    view: "standart",
  },
  {
    code: "KeyH",
    keyBig: "H",
    keySmall: "h",
    keyBigUa: "Р",
    keySmallUa: "р",
    view: "standart",
  },
  {
    code: "KeyJ",
    keyBig: "J",
    keySmall: "j",
    keyBigUa: "О",
    keySmallUa: "о",
    view: "standart",
  },
  {
    code: "KeyK",
    keyBig: "K",
    keySmall: "k",
    keyBigUa: "Л",
    keySmallUa: "л",
    view: "standart",
  },
  {
    code: "KeyL",
    keyBig: "L",
    keySmall: "l",
    keyBigUa: "Д",
    keySmallUa: "д",
    view: "standart",
  },
  {
    code: "Semicolon",
    keyBig: ";",
    keySmall: ";",
    keyBigUa: "Ж",
    keySmallUa: "ж",
    view: "standart",
  },
  {
    code: "Quote",
    keyBig: "'",
    keySmall: "'",
    keyBigUa: "Є",
    keySmallUa: "є",
    view: "standart",
  },
];
