export const third = [
  {
    code: "KeyZ",
    keyBig: "Z",
    keySmall: "z",
    keyBigUa: "Я",
    keySmallUa: "я",
    view: "standart",
  },
  {
    code: "KeyX",
    keyBig: "X",
    keySmall: "x",
    keyBigUa: "Ч",
    keySmallUa: "ч",
    view: "standart",
  },
  {
    code: "KeyC",
    keyBig: "C",
    keySmall: "c",
    keyBigUa: "С",
    keySmallUa: "с",
    view: "standart",
  },
  {
    code: "KeyV",
    keyBig: "V",
    keySmall: "v",
    keyBigUa: "М",
    keySmallUa: "м",
    view: "standart",
  },
  {
    code: "KeyB",
    keyBig: "B",
    keySmall: "b",
    keyBigUa: "И",
    keySmallUa: "и",
    view: "standart",
  },
  {
    code: "KeyN",
    keyBig: "N",
    keySmall: "n",
    keyBigUa: "Т",
    keySmallUa: "т",
    view: "standart",
  },
  {
    code: "KeyM",
    keyBig: "M",
    keySmall: "m",
    keyBigUa: "Ь",
    keySmallUa: "ь",
    view: "standart",
  },
  {
    code: "Comma",
    keyBig: ",",
    keySmall: ",",
    keyBigUa: "Б",
    keySmallUa: "б",
    view: "standart",
  },
  {
    code: "Period",
    keyBig: ".",
    keySmall: ".",
    keyBigUa: "Ю",
    keySmallUa: "ю",
    view: "standart",
  },
  {
    code: "Slash",
    keyBig: "/",
    keySmall: "/",
    keyBigUa: ".",
    keySmallUa: ".",
    view: "standart",
  },
];
